---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

silent: true


vars:
  SYNC_INTERVAL: "{{env \"SYNC_INTERVAL\" | default \"10\"}}"
  GIT_REPO_URL: "{{env \"GIT_REPO_URL\"}}"


includes:
  ssh: .taskfiles/ssh
  git: .taskfiles/git


tasks:
  default: go-task --list

  sync:
    desc: single sync
    cmds:
      - task: ssh:setup
      - task: git:clone
      - task: git:sync

  watch:
    desc: continuous sync
    cmds:
      - task: ssh:setup
      - task: git:clone
      - task: git:sync
      - while :; do
          sleep {{.SYNC_INTERVAL}};
          go-task git:sync;
        done
